"""Added property book_title in borrow model

Revision ID: 19f8c67c0273
Revises: 2bf6cb8671a3
Create Date: 2025-11-10 21:00:38.414691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f8c67c0273'
down_revision: Union[str, Sequence[str], None] = '2bf6cb8671a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
