"""Added timezone in borrow model

Revision ID: 2bf6cb8671a3
Revises: a8ad331b0323
Create Date: 2025-11-10 20:47:53.285843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf6cb8671a3'
down_revision: Union[str, Sequence[str], None] = 'a8ad331b0323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
